hash-format = "sha256"

[[files]]
file = "config/VillagerConfig/villagerconfig.json5"
hash = "c09b0518db297ec1bd61d0ff468e691734978dd1a2853e49ba6b74d0ed3cb8dc"

[[files]]
file = "config/WindowTitleChanger/config.json5"
hash = "07996395a02f8e4c4d8078e4b7614d56282e0048f1cee5ab4354c1186004eff2"

[[files]]
file = "config/WindowTitleChanger/icons/icon16.png"
hash = "15379da9cb401439d3dc5facf13d8ee93a33418991dfda5b403344937040aa74"

[[files]]
file = "config/WindowTitleChanger/icons/icon32.png"
hash = "ee95953ff556f083a8f28e59e7efe507d6f33626ac3a9788c84fe2a1ca74ab70"

[[files]]
file = "config/createaddition-common.toml"
hash = "bc35e897cd74bac7406ae809f5979bf068307c07d1cf7fa2bca7e537c1c165aa"

[[files]]
file = "config/darkness.properties"
hash = "6c1d90b6c84c82336d46c6407c22e6441a8c7b49f7c0099a7f0a51f46edff9b3"

[[files]]
file = "config/harvest.json"
hash = "cdacac68561cf7bfcf6ef8710d8108442a2ea8a6ff14686d8f23fbdfc8b125b4"

[[files]]
file = "config/interactic.json5"
hash = "74e959775fb0780dc1afbb70206ea115fd91a2d93ce58e4fe6799e5129220638"

[[files]]
file = "config/modmenu.json"
hash = "f8668702eedecd2cfba95306e2909adb1719c6def92717df1e1779a3e635900f"

[[files]]
file = "config/numismatic-overhaul.json5"
hash = "5c267ddf5f5f89798d5df7fc3f7d6cb81b1595e61aadf41af611d2ff1c7c8c10"

[[files]]
file = "config/presencefootsteps/updater.json"
hash = "1e7c61df09c105e1eeca8cf3dcbdfeb976700e9904bcb3983fc7791adb7fad2e"

[[files]]
file = "config/presencefootsteps/userconfig.json"
hash = "7356d7a47eb0669301bdc8586e16399fe5c1e30d4c0d6eca6a016790851bb805"

[[files]]
file = "config/semblance.properties"
hash = "0eb5c22962d4bd785b5003fb035eb7bdc6744f1db3ba9074d46c60280cb47498"

[[files]]
file = "config/servercore.toml"
hash = "3d05f2fde600b9bb5a67af9b385e12a66a4f9e523658b3b61af02123202072b0"

[[files]]
file = "config/servertick.toml"
hash = "86cbe39fd14aabad542ffa7deb2148346e1fc7646a386696191c8e1620579c96"

[[files]]
file = "config/styled-chat.json"
hash = "8cbe53deb61a0f55eb61a8a10cd22725371d6916dd4393b9474e7338913b109c"

[[files]]
file = "mods/alternate-current.toml"
hash = "e2030b544b5a68ca886c502b2c6b5e6e02d5480173c7c0d4899009c845ca231b"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.toml"
hash = "378d61c3fdb3a5839a3b4f8e3e86bb44c040cc2be0aa5566eab8e03c01b7c4c0"
metafile = true

[[files]]
file = "mods/appleskin.toml"
hash = "0940f87fc8d934433725019169945f77b7c27bd4a23828286ffb68aac4810a6c"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff27996cf1f612781b5a3130c31ace4977d4b6d1cf375ee5ed6048830e2d53bc"
metafile = true

[[files]]
file = "mods/bedspreads-fabric.toml"
hash = "335ae666f95c0916d3573e35daba855f0dfe2f39e9b5a16a35b7318ab24107a2"
metafile = true

[[files]]
file = "mods/better-bad-omen.toml"
hash = "8fbd67fe5eae199dece105b27b8cca3e6815648099c33855f194d7d635ec5834"
metafile = true

[[files]]
file = "mods/boat-fall.toml"
hash = "fd10a35276aa7cd415906946d42fe46bfbfc580661333dfb83f08490f21d52c2"
metafile = true

[[files]]
file = "mods/chalk.toml"
hash = "9d964354c8312bf29747e4ad32fb3967f868b8ada1de92ed6b25742eb87ea3e8"
metafile = true

[[files]]
file = "mods/cleancut.pw.toml"
hash = "a1497ac93d23e54a85636f91140656e2c8d9bd45fb925963132880289c1de8b4"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "4ed6f98bd55bde1e076f864ba2b3918710ef2ee664ca332fd538c6ca27f280a0"
metafile = true

[[files]]
file = "mods/controlling.toml"
hash = "856583ed59b9853f04a69db0e4c376cad017e83240962a2e8d0d58dfe20df78d"
metafile = true

[[files]]
file = "mods/create-fabric.toml"
hash = "88a8c9ca3ed1277f5304a12f1e318076ae51e8873daea640e7a1e01b23d9f084"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6296824efedc26529ffde9c9f462b9d2c397de447b8a8827724863ffe3654d3"
metafile = true

[[files]]
file = "mods/dark-graph.toml"
hash = "fed19a27f499c25b6a0e56e7da188f914474bd40e60e96d535b663b3fb101927"
metafile = true

[[files]]
file = "mods/dark-loading-screen.toml"
hash = "4754813e43ba908c01de0a8deccdd427367cbaa0502e8ebeb633049c6361c3f3"
metafile = true

[[files]]
file = "mods/dcwa.toml"
hash = "60134dc6ce2d30c5a16367a1b21d32d3964f5fd508654d7f4232471d9aad8163"
metafile = true

[[files]]
file = "mods/extended-clouds.pw.toml"
hash = "dd0905b3ca5fcffc9680217cb390ab187ef28eae006bee49d6ceafcfcf8f0db8"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "e827579af29e5db22e80d7dfc61aee87e004c23880eff6a1391fa3e265dd3f56"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "d2fbaf45c8aed07525a3d592a02242db2c2a9a76cf6c995585835282e87d24f5"
metafile = true

[[files]]
file = "mods/fallingleaves.toml"
hash = "a2f5ac9241681699e8bcd7da4c90e9899686290f883a63c56f7009f18f731e7e"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/fixed-waterlogging.toml"
hash = "f54bf9bfddb3c546a85ccb6e91c591afb30d34b1be9bda9a0e72a942b3ad41de"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.toml"
hash = "d77d0fe2df4d0c37048b0cf0dbaf9ff2a5a3d1d15a3d48c61bee8e8c9e797d9e"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "dd62536d072d1ba186f7b7df71b0903143433e3881a40e93f4852ecb5ea89294"
metafile = true

[[files]]
file = "mods/interactic.toml"
hash = "e44b74c440a66bbb0f429d8439a4395885a68f7f31f29ccfc103a520587b0702"
metafile = true

[[files]]
file = "mods/jumpoverfences.toml"
hash = "72036cf085640bf2b61564f85b391686a5fab9f9077fd7703609e41efa61ba12"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "ced9beca851fd90343eec56eb8276ebe33d32228f00ac8877cfffe0a12cec934"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "158c40f09b2ed4fe14f5f2925751796fe11f6baee7e1ac7f35931ad831631a3d"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "83541b1d3e1e936638a6938eb505bf0f508c13aed7f8416af8d064ffc7cda4dc"
metafile = true

[[files]]
file = "mods/mealapi.toml"
hash = "b10350c90e82c86b06fbaa54c430daff02eb3878cf0082c9f84b54b39a005a94"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "8f501b0b0f968e3b4819219c5fd5c656500bb0a2736cafff092ce7279fe85574"
metafile = true

[[files]]
file = "mods/no-player-labels.toml"
hash = "6ec6300387c9ad315c1ff74b58f12771cbd9cea9b806c825bd5bede0cff1848b"
metafile = true

[[files]]
file = "mods/no-telemetry.toml"
hash = "e8814a83e235e82705f7fbccc5f91c8b1a0b679af439e38ab48f0ddafa623db7"
metafile = true

[[files]]
file = "mods/numismatic-overhaul.pw.toml"
hash = "21a97d8ea7a2015354259ac446194002beb6c5270939c5411796a8c40b07473d"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "51b735f00031dc7ddbb390dae266953bfbab4e7a3018a824751b149757489a4a"
metafile = true

[[files]]
file = "mods/phonos.toml"
hash = "848b034cd45ed1aaaa9830f24a9fa33d1b7cd1a5f8a785bbcbc80cad410b6e00"
metafile = true

[[files]]
file = "mods/presence-footsteps.toml"
hash = "525252bb860d002a1985a4ffbb4cee19d727dc01bc78eaee0d3881e7bfff2eca"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "3efeee5800eb609d02837d650d3d7724c681053cdb886a8cabe5988d563e034f"
metafile = true

[[files]]
file = "mods/sandwichable.toml"
hash = "05ac14b7e41f25d5492073c716e5cdd648b1e4286282690f5485b6c300500874"
metafile = true

[[files]]
file = "mods/semblance.toml"
hash = "81cb2bb9a5525d321df2bea2ea5cfc3ccedfa649ac28d2be00403a397c417276"
metafile = true

[[files]]
file = "mods/servercore.toml"
hash = "c04e7a759cc12522f665a33cadf0fd8f182d1918ea17b7e818fee7575fca9cef"
metafile = true

[[files]]
file = "mods/servertick.toml"
hash = "7a38684ee548a4cd27e4419f5632dd3ba0f4f7f250a0070e2abfc1e5c8907340"
metafile = true

[[files]]
file = "mods/sheep-consistency.toml"
hash = "d6247196156f8d81b42229a9ffc933457e0475de6c8a3d1de4c893dd5305e2d2"
metafile = true

[[files]]
file = "mods/simple-voice-chat.toml"
hash = "9346d09f897be45df79ad6af92e38f34f650ca557e65bc199f629021bbcff915"
metafile = true

[[files]]
file = "mods/simplerharvest.toml"
hash = "05ba1679074ec1c855e7c7042ade3dcd3a77cf2a19acf67b2bfeeb291f43fdf3"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.toml"
hash = "1fe9aa5d3d49e8a426236ba189b751a0421b8ea56eb890b9dc794f53aea915d4"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "722031c0ae5d2de71783d6c4bfbf1c5cd25c65e55cb42d8bb4f7cadf478c4368"
metafile = true

[[files]]
file = "mods/styled-chat.toml"
hash = "7c10e2599f25e36dab5f53cabbe3213082c853495b3dfc101a36b9dd7b9758b3"
metafile = true

[[files]]
file = "mods/styledplayerlist.toml"
hash = "6df3f3a64d0499d11583b91741ff31f908e55c688958f039bf59d707161d56cc"
metafile = true

[[files]]
file = "mods/true-darkness.pw.toml"
hash = "fc08346de3d1f134796e6b8a88470cfca55f610445e210e0fced2fd2caaff378"
metafile = true

[[files]]
file = "mods/villagerconfig.toml"
hash = "a6263ae7ff8961da42fc795061cbd779831c7b3e536782cf52850c066c62a580"
metafile = true

[[files]]
file = "mods/window-title-changer.toml"
hash = "6b5c208767ccc42f96c27c7a57f2f27b9d0bea0b2fcef1b78d2439fd18458909"
metafile = true

[[files]]
file = "mods/yungs-api-fabric.toml"
hash = "83cbf868ae2dcd47190114b33904be6fe4d566a32d21047256388cacc688f71a"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-fabric.toml"
hash = "3c78fbc0aeba672424eb457f0fabdf3b92ba2975066f089e7e769b8d32f828f8"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-fabric.toml"
hash = "13eff10a7835e007666cd6c7e518465312c003a306e531f47d9343893c4f2582"
metafile = true
