hash-format = "sha256"

[[files]]
file = "config/VillagerConfig/villagerconfig.json5"
hash = "c09b0518db297ec1bd61d0ff468e691734978dd1a2853e49ba6b74d0ed3cb8dc"

[[files]]
file = "config/WindowTitleChanger/config.json5"
hash = "07996395a02f8e4c4d8078e4b7614d56282e0048f1cee5ab4354c1186004eff2"

[[files]]
file = "config/WindowTitleChanger/icons/icon16.png"
hash = "15379da9cb401439d3dc5facf13d8ee93a33418991dfda5b403344937040aa74"

[[files]]
file = "config/WindowTitleChanger/icons/icon32.png"
hash = "ee95953ff556f083a8f28e59e7efe507d6f33626ac3a9788c84fe2a1ca74ab70"

[[files]]
file = "config/darkness.properties"
hash = "6c1d90b6c84c82336d46c6407c22e6441a8c7b49f7c0099a7f0a51f46edff9b3"

[[files]]
file = "config/interactic.json5"
hash = "74e959775fb0780dc1afbb70206ea115fd91a2d93ce58e4fe6799e5129220638"

[[files]]
file = "config/modmenu.json"
hash = "f8668702eedecd2cfba95306e2909adb1719c6def92717df1e1779a3e635900f"

[[files]]
file = "config/presencefootsteps/updater.json"
hash = "1e7c61df09c105e1eeca8cf3dcbdfeb976700e9904bcb3983fc7791adb7fad2e"

[[files]]
file = "config/presencefootsteps/userconfig.json"
hash = "7356d7a47eb0669301bdc8586e16399fe5c1e30d4c0d6eca6a016790851bb805"

[[files]]
file = "config/semblance.properties"
hash = "0eb5c22962d4bd785b5003fb035eb7bdc6744f1db3ba9074d46c60280cb47498"

[[files]]
file = "config/servercore.toml"
hash = "3d05f2fde600b9bb5a67af9b385e12a66a4f9e523658b3b61af02123202072b0"

[[files]]
file = "config/servertick.toml"
hash = "86cbe39fd14aabad542ffa7deb2148346e1fc7646a386696191c8e1620579c96"

[[files]]
file = "config/styled-chat.json"
hash = "8cbe53deb61a0f55eb61a8a10cd22725371d6916dd4393b9474e7338913b109c"

[[files]]
file = "mods/alternate-current.toml"
hash = "62d859bdfed94ea89b998f907e7e67d6def0400c32dbee2d9938bbe39ba395d7"
metafile = true

[[files]]
file = "mods/appleskin.toml"
hash = "0940f87fc8d934433725019169945f77b7c27bd4a23828286ffb68aac4810a6c"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "612eb5b02d9f18e9c5327bb96373c692c72c9ebbae3541eea03feda76dcd764a"
metafile = true

[[files]]
file = "mods/boat-fall.toml"
hash = "fd10a35276aa7cd415906946d42fe46bfbfc580661333dfb83f08490f21d52c2"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "8201c0a16ace201405172e56292843cc99d8d675f1e323684943b9cee393acb1"
metafile = true

[[files]]
file = "mods/controlling.toml"
hash = "856583ed59b9853f04a69db0e4c376cad017e83240962a2e8d0d58dfe20df78d"
metafile = true

[[files]]
file = "mods/create-mc1.18.2_v0.4.1+539-mchorizons.jar"
hash = "504dd69992c9b91e2b7cc9df3c05859294c5315aa112e4c251120a2a42e0c7c4"

[[files]]
file = "mods/dark-graph.toml"
hash = "fed19a27f499c25b6a0e56e7da188f914474bd40e60e96d535b663b3fb101927"
metafile = true

[[files]]
file = "mods/dark-loading-screen.toml"
hash = "4754813e43ba908c01de0a8deccdd427367cbaa0502e8ebeb633049c6361c3f3"
metafile = true

[[files]]
file = "mods/darkness-fabric-mc118-2.0.89-mchorizons.jar"
hash = "0d235999df7cc1f2f0923d1100ac653c494713df4c10259d89a42aeacc4caa70"

[[files]]
file = "mods/dcwa.toml"
hash = "60134dc6ce2d30c5a16367a1b21d32d3964f5fd508654d7f4232471d9aad8163"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "f4e1da9342cd15c7c79835c952dce47b8786f3c393b9cf644ef3b5ed638ae052"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "d2fbaf45c8aed07525a3d592a02242db2c2a9a76cf6c995585835282e87d24f5"
metafile = true

[[files]]
file = "mods/fallingleaves.toml"
hash = "0348dc80342aa0b781389fadd179036d8d05362c65f7ef42287a4bee7418cf01"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/fixed-waterlogging.toml"
hash = "f54bf9bfddb3c546a85ccb6e91c591afb30d34b1be9bda9a0e72a942b3ad41de"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.toml"
hash = "d77d0fe2df4d0c37048b0cf0dbaf9ff2a5a3d1d15a3d48c61bee8e8c9e797d9e"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "735bb894e8fd0430de8fe331347ff24c5c64643bc65f2c040f7a82fb17e8b826"
metafile = true

[[files]]
file = "mods/interactic.toml"
hash = "e44b74c440a66bbb0f429d8439a4395885a68f7f31f29ccfc103a520587b0702"
metafile = true

[[files]]
file = "mods/jumpoverfences.toml"
hash = "72036cf085640bf2b61564f85b391686a5fab9f9077fd7703609e41efa61ba12"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "ced9beca851fd90343eec56eb8276ebe33d32228f00ac8877cfffe0a12cec934"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "158c40f09b2ed4fe14f5f2925751796fe11f6baee7e1ac7f35931ad831631a3d"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "8243fcb2221942db16259a029d2964ca41d7a336fccc60464597d9f0d6699529"
metafile = true

[[files]]
file = "mods/mealapi.toml"
hash = "b10350c90e82c86b06fbaa54c430daff02eb3878cf0082c9f84b54b39a005a94"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "a73f71d58f3a3c5f01e86f32209d03d002f73768eedff9cb6f9cbd150ecb6361"
metafile = true

[[files]]
file = "mods/no-player-labels.toml"
hash = "6ec6300387c9ad315c1ff74b58f12771cbd9cea9b806c825bd5bede0cff1848b"
metafile = true

[[files]]
file = "mods/no-telemetry.toml"
hash = "e8814a83e235e82705f7fbccc5f91c8b1a0b679af439e38ab48f0ddafa623db7"
metafile = true

[[files]]
file = "mods/phonos.toml"
hash = "848b034cd45ed1aaaa9830f24a9fa33d1b7cd1a5f8a785bbcbc80cad410b6e00"
metafile = true

[[files]]
file = "mods/presence-footsteps.toml"
hash = "525252bb860d002a1985a4ffbb4cee19d727dc01bc78eaee0d3881e7bfff2eca"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
hash = "fb3132af2dd8a755ad4d23d93b99166751f4c81ea1f9a74f194119d148f73844"
metafile = true

[[files]]
file = "mods/sandwichable.toml"
hash = "05ac14b7e41f25d5492073c716e5cdd648b1e4286282690f5485b6c300500874"
metafile = true

[[files]]
file = "mods/semblance.toml"
hash = "81cb2bb9a5525d321df2bea2ea5cfc3ccedfa649ac28d2be00403a397c417276"
metafile = true

[[files]]
file = "mods/servercore.toml"
hash = "c04e7a759cc12522f665a33cadf0fd8f182d1918ea17b7e818fee7575fca9cef"
metafile = true

[[files]]
file = "mods/servertick.toml"
hash = "7a38684ee548a4cd27e4419f5632dd3ba0f4f7f250a0070e2abfc1e5c8907340"
metafile = true

[[files]]
file = "mods/simple-voice-chat.toml"
hash = "676194d6e58c6d8b37272ddbbfff1c0336cd7c379509569e9e60e39111b61cdf"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.toml"
hash = "ef3dc3153d1ef10b6ac6cd061fdeb0c50b55beaf5b65a6bd5e68fdcd40cccf7d"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "722031c0ae5d2de71783d6c4bfbf1c5cd25c65e55cb42d8bb4f7cadf478c4368"
metafile = true

[[files]]
file = "mods/styled-chat.toml"
hash = "7c10e2599f25e36dab5f53cabbe3213082c853495b3dfc101a36b9dd7b9758b3"
metafile = true

[[files]]
file = "mods/styledplayerlist.toml"
hash = "6df3f3a64d0499d11583b91741ff31f908e55c688958f039bf59d707161d56cc"
metafile = true

[[files]]
file = "mods/villagerconfig.toml"
hash = "a6263ae7ff8961da42fc795061cbd779831c7b3e536782cf52850c066c62a580"
metafile = true

[[files]]
file = "mods/window-title-changer.toml"
hash = "6b5c208767ccc42f96c27c7a57f2f27b9d0bea0b2fcef1b78d2439fd18458909"
metafile = true

[[files]]
file = "mods/yungs-api-fabric.toml"
hash = "83cbf868ae2dcd47190114b33904be6fe4d566a32d21047256388cacc688f71a"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-fabric.toml"
hash = "6d72fe92f96af7ca4dfb82a852a69004ba8b13ab319eeb14fa4bdcf3590e10c3"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds-fabric.toml"
hash = "13eff10a7835e007666cd6c7e518465312c003a306e531f47d9343893c4f2582"
metafile = true
