name = "MCHorizons"
author = "EcoBuilder13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be943496baebada5130d4a3d1502dcbb1828e73db9661a9ba9bd115441246411"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
